### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by zek-c** [ATLSkid/Exterium-V2-Cracked#1]
guys pls dont downlaod its a virus lol avg anti saved me

**Comment by ATLSkid** [comment]
Its not a "virus" it is a false positive, you are simply a retard

**Comment by zynhh** [comment]
hi ATLS, out of all the games listed, COD/WZ is the only one I care for. I have gotten hwid permabanned for all CODs from just accumulated reports system only after 40 days timeplayed on MWII alone. I spent way too much time trying to figure it all out and did everything I could. Point is Im beyond exhausted. So lastly, before going ahead and reset my pc with eventually having a very few paid spoofers in mind, I was wondering if you had any better ideas to help me out.  

Thanks!
